### ISSUE TITLE
[Bug]: Run time warnings

### ISSUE THREAD

**Issue by siberowl** [Amijakan/mochatto#130]
### Expected Behaviour

No warnings during run time.

### Actual Behaviour

There are run time warnings.

### Additional Info

It happens after Room Page renders.

### Relevant log output

```shell
DevTools failed to load source map: Could not load content for chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/sourceMap/chrome/iframe_handler.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

DevTools failed to load source map: Could not load content for chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/sourceMap/chrome/content.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

Warning: React does not recognize the `iconsSize` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `iconssize` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at http://localhost:4500/static/js/vendors~main.chunk.js:69331:77
    at Transition (http://localhost:4500/static/js/vendors~main.chunk.js:58939:30)
    at Notification (http://localhost:4500/static/js/vendors~main.chunk.js:9335:5)
    at div
    at http://localhost:4500/static/js/vendors~main.chunk.js:69331:77
    at RoomTemplate (http://localhost:4500/static/js/main.chunk.js:4628:3)
    at RoomPage (http://localhost:4500/static/js/main.chunk.js:3884:3)
    at Pages (http://localhost:4500/static/js/main.chunk.js:4330:81)
    at Route (http://localhost:4500/static/js/vendors~main.chunk.js:52512:29)
    at Switch (http://localhost:4500/static/js/vendors~main.chunk.js:52714:29)
    at Router (http://localhost:4500/static/js/vendors~main.chunk.js:52147:30)
    at BrowserRouter (http://localhost:4500/static/js/vendors~main.chunk.js:51767:35)
    at UserInfoProvider (http://localhost:4500/static/js/main.chunk.js:2974:3)
    at DeviceProvider (http://localhost:4500/static/js/main.chunk.js:2512:3)
    at PositionsProvider (http://localhost:4500/static/js/main.chunk.js:2647:3)
    at SocketProvider (http://localhost:4500/static/js/main.chunk.js:2829:3)
    at Providers (http://localhost:4500/static/js/main.chunk.js:3161:3)
    at div
    at App
    at DevProvider (http://localhost:4500/static/js/vendors~main.chunk.js:68996:30)

Warning: React does not recognize the `iconSize` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `iconsize` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at http://localhost:4500/static/js/vendors~main.chunk.js:69331:77
    at Transition (http://localhost:4500/static/js/vendors~main.chunk.js:58939:30)
    at Notification (http://localhost:4500/static/js/vendors~main.chunk.js:9335:5)
    at div
    at http://localhost:4500/static/js/vendors~main.chunk.js:69331:77
    at RoomTemplate (http://localhost:4500/static/js/main.chunk.js:4628:3)
    at RoomPage (http://localhost:4500/static/js/main.chunk.js:3884:3)
    at Pages (http://localhost:4500/static/js/main.chunk.js:4330:81)
    at Route (http://localhost:4500/static/js/vendors~main.chunk.js:52512:29)
    at Switch (http://localhost:4500/static/js/vendors~main.chunk.js:52714:29)
    at Router (http://localhost:4500/static/js/vendors~main.chunk.js:52147:30)
    at BrowserRouter (http://localhost:4500/static/js/vendors~main.chunk.js:51767:35)
    at UserInfoProvider (http://localhost:4500/static/js/main.chunk.js:2974:3)
    at DeviceProvider (http://localhost:4500/static/js/main.chunk.js:2512:3)
    at PositionsProvider (http://localhost:4500/static/js/main.chunk.js:2647:3)
    at SocketProvider (http://localhost:4500/static/js/main.chunk.js:2829:3)
    at Providers (http://localhost:4500/static/js/main.chunk.js:3161:3)
    at div
    at App
    at DevProvider (http://localhost:4500/static/js/vendors~main.chunk.js:68996:30)

Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at div
    at http://localhost:4500/static/js/vendors~main.chunk.js:69331:77
    at Transition (http://localhost:4500/static/js/vendors~main.chunk.js:58939:30)
    at Notification (http://localhost:4500/static/js/vendors~main.chunk.js:9335:5)
    at div
    at http://localhost:4500/static/js/vendors~main.chunk.js:69331:77
    at RoomTemplate (http://localhost:4500/static/js/main.chunk.js:4628:3)
    at RoomPage (http://localhost:4500/static/js/main.chunk.js:3884:3)
    at Pages (http://localhost:4500/static/js/main.chunk.js:4330:81)
    at Route (http://localhost:4500/static/js/vendors~main.chunk.js:52512:29)
    at Switch (http://localhost:4500/static/js/vendors~main.chunk.js:52714:29)
    at Router (http://localhost:4500/static/js/vendors~main.chunk.js:52147:30)
    at BrowserRouter (http://localhost:4500/static/js/vendors~main.chunk.js:51767:35)
    at UserInfoProvider (http://localhost:4500/static/js/main.chunk.js:2974:3)
    at DeviceProvider (http://localhost:4500/static/js/main.chunk.js:2512:3)
    at PositionsProvider (http://localhost:4500/static/js/main.chunk.js:2647:3)
    at SocketProvider (http://localhost:4500/static/js/main.chunk.js:2829:3)
    at Providers (http://localhost:4500/static/js/main.chunk.js:3161:3)
    at div
    at App
    at DevProvider (http://localhost:4500/static/js/vendors~main.chunk.js:68996:30)
```

**Comment by siberowl** [comment]
Not fixed yet.

**Comment by siberowl** [comment]
Seems like an issue with atomize hmm...
